use std::{
    collections::{HashMap, HashSet},
    fs::{self, DirEntry, File},
    io::{BufRead, BufReader, BufWriter, Read, Write},
    path::{Path, PathBuf},
};

use miette::{miette, Context, IntoDiagnostic, LabeledSpan, MietteDiagnostic, Severity};

const RULES_PYTHON_INIT_PATH: &str = "runfiles/__init__.py";
const RULES_PYTHON_RUNFILES_INIT_SHIM: &str = r#"
# Generated by rules_py venv for rules_python compatibility
# See: https://github.com/bazelbuild/rules_python/pull/2115
# See: https://github.com/aspect-build/rules_py/issues/377
from . import runfiles
def _FindPythonRunfilesRoot():
    root = __file__
    # The original implementation of this function in rules_python expects the runfiles root to be 4 directories up from the current file.
    # but in rules_py there is additional two segments that it needs to go up to  find the runfiles root.
    # bazel-bin/py/tests/external-deps/foo.runfiles/.foo.venv/lib/python3.9/site-packages/runfiles
    # ╰─────────────────────┬─────────────────────╯╰───┬───╯╰─────────────┬─────────────╯╰───┬───╯
    #             bazel runfiles root              venv root    Python packages root   Python package
    
    for _ in range("rules_python/python/runfiles/runfiles.py".count("/") + 3):
        root = os.path.dirname(root)
    return root

runfiles._FindPythonRunfilesRoot = _FindPythonRunfilesRoot

from .runfiles import *
"#;

/// Strategy that will be used when creating the virtual env symlink and
/// a collision is found.
#[derive(Default, Debug, PartialEq)]
pub enum CollisionResolutionStrategy {
    /// Collisions cause a hard error.
    #[default]
    Error,

    /// The last file to provide a target wins.
    /// If inner is true, then a warning is produced, otherwise the last target silently wins.
    LastWins(bool),
}

/// Options for the creation of the `site-packages` folder layout.
#[derive(Default, Debug)]
pub struct SitePackageOptions {
    /// Destination path, where the `site-package` folder lives.
    pub dest: PathBuf,

    /// Collision strategy determining the action taken when sylinks in the venv collide.
    pub collision_strategy: CollisionResolutionStrategy,
}

pub struct PthFile {
    pub src: PathBuf,
    pub prefix: Option<String>,
}

impl PthFile {
    pub fn new(src: &Path, prefix: Option<String>) -> PthFile {
        Self {
            src: src.to_path_buf(),
            prefix,
        }
    }

    // This is the _old_ machinery for setting up a virtualenv, which assumes
    // that the path file consists of pre-relativized paths. The new machinery
    // does that math on the Rust side rather than on the Bazel side, so the two
    // are `.pth` file incompatible.
    //
    // .pth-to-external strategy: instead of creating symlinks (even top-level
    // ones), write .pth entries pointing directly to the canonicalized
    // external/ paths where real files live. This bypasses both symlink layers
    // (venv→runfiles and runfiles→external), eliminating all readlink()
    // overhead during Python imports.
    //
    // For namespace conflicts (e.g. nvidia-* packages on Linux that all
    // provide `nvidia/`), fall back to recursive symlink-merging so all
    // providers contribute their files under the shared name.
    pub fn set_up_site_packages_dynamic(&self, opts: SitePackageOptions) -> miette::Result<()> {
        let dest = &opts.dest;

        let source_pth = File::open(self.src.as_path())
            .into_diagnostic()
            .wrap_err("Unable to open source .pth file")?;
        let dest_pth = File::create(dest.join(self.src.file_name().expect(".pth must be a file")))
            .into_diagnostic()
            .wrap_err("Unable to create destination .pth file")?;

        let mut reader = BufReader::new(source_pth);
        let mut writer = BufWriter::new(dest_pth);
        let path_prefix = self.prefix.as_ref().map(|pre| Path::new(pre));

        // Names to skip entirely (never symlink, never count as conflicts).
        let skip_names: HashSet<&str> =
            HashSet::from(["__pycache__", "__init__.py", "__pypackages__"]);

        // Suffixes to exclude from conflict detection but still include via .pth.
        let metadata_suffixes = [".dist-info", ".egg-info"];

        // Phase 1: Read all entries; for site-packages dirs, resolve to
        // external/ via file-symlink probing and collect top-level names.
        let mut site_external_dirs: Vec<PathBuf> = Vec::new();
        let mut non_site_entries: Vec<PathBuf> = Vec::new();
        let mut toplevel_to_sources: HashMap<String, Vec<PathBuf>> = HashMap::new();

        let mut line = String::new();
        while reader.read_line(&mut line).unwrap() > 0 {
            let entry = path_prefix
                .map(|pre| pre.join(line.trim()))
                .unwrap_or_else(|| PathBuf::from(line.trim()));

            line.clear();

            let is_site = entry.file_name().map_or(false, |n| n == "site-packages");
            if is_site {
                let runfiles_dir = dest
                    .join(&entry)
                    .canonicalize()
                    .into_diagnostic()
                    .wrap_err(format!(
                        "Unable to resolve site-packages path {} relative to {}",
                        entry.display(),
                        dest.display(),
                    ))?;

                // Resolve to external/ by probing a file symlink inside.
                // Falls back to runfiles path if no symlinks found (e.g. all
                // files are generated, or directory is already external/).
                let external_dir = resolve_to_external(&runfiles_dir)
                    .unwrap_or_else(|| runfiles_dir.clone());

                for child in fs::read_dir(&runfiles_dir).into_diagnostic().wrap_err(format!(
                    "Unable to read site-packages directory {}",
                    runfiles_dir.display()
                ))? {
                    let child = child.into_diagnostic()?;
                    let name = child.file_name().to_string_lossy().to_string();
                    if skip_names.contains(name.as_str())
                        || metadata_suffixes.iter().any(|s| name.ends_with(s))
                    {
                        continue;
                    }
                    toplevel_to_sources
                        .entry(name)
                        .or_default()
                        .push(runfiles_dir.clone());
                }
                site_external_dirs.push(external_dir);
            } else {
                non_site_entries.push(entry);
            }
        }

        // Phase 2: Identify conflicting names (provided by more than one source dir).
        let conflicting_names: HashSet<String> = toplevel_to_sources
            .iter()
            .filter(|(_, sources)| sources.len() > 1)
            .map(|(name, _)| name.clone())
            .collect();

        // Phase 3: Write .pth entries and handle conflicts.
        //
        // Non-site-packages entries (first-party code): .pth lines unchanged.
        for entry in &non_site_entries {
            writeln!(writer, "{}", entry.to_string_lossy())
                .into_diagnostic()
                .wrap_err("Unable to write new .pth file entry")?;
        }

        // Site-packages entries: write a .pth line pointing directly to the
        // external/ path where real files live. Python adds this to sys.path,
        // so all packages are importable with zero symlink traversal.
        //
        // For conflicting names (e.g. nvidia-* on Linux), additionally
        // symlink-merge into the venv's site-packages via the runfiles dir.
        // Site-packages is earlier on sys.path than .pth additions, so the
        // symlinked version takes precedence for conflicting names.
        for external_dir in &site_external_dirs {
            writeln!(writer, "{}", external_dir.to_string_lossy())
                .into_diagnostic()
                .wrap_err("Unable to write .pth entry for site-packages")?;
        }

        // Handle namespace conflicts (e.g. nvidia-* packages on Linux all
        // providing nvidia/). Instead of scanning every site-packages dir and
        // creating per-file recursive symlinks, we use targeted directory-level
        // merging:
        //
        // 1. Only look at directories that actually contribute each conflict
        //    (from toplevel_to_sources), skipping the ~176 that don't.
        // 2. Collect children across all contributing directories.
        // 3. Create directory-level symlinks for unique children (e.g.
        //    nvidia/cublas/ comes only from nvidia-cublas-cu12).
        // 4. Recurse into sub-directories that themselves conflict across
        //    sources, handling arbitrary nesting depth.
        // 5. Resolve all symlink targets to their canonical external/ paths
        //    so the venv never chains through runfiles symlinks.
        //
        // For 15 nvidia-* packages this creates ~15 directory symlinks
        // instead of ~300 file-level symlinks, and avoids scanning ~176
        // unrelated site-packages directories entirely.
        if !conflicting_names.is_empty() {
            for name in &conflicting_names {
                let source_dirs: Vec<PathBuf> = toplevel_to_sources[name]
                    .iter()
                    .map(|sp| sp.join(name))
                    .collect();

                merge_namespace_conflict(
                    &source_dirs,
                    &dest.join(name),
                    &opts.collision_strategy,
                )?;
            }
        }

        Ok(())
    }
}

/// Merge multiple source directories that share a namespace (e.g. nvidia/ from
/// 15 nvidia-* packages) into a single destination directory using directory-level
/// symlinks. Only recurses into sub-directories that themselves have conflicts
/// across sources, handling arbitrary nesting depth.
///
/// All symlink targets are resolved to their canonical paths (typically in
/// Bazel's external/ directory) to avoid chaining through runfiles symlinks.
fn merge_namespace_conflict(
    sources: &[PathBuf],
    dest_dir: &Path,
    collision_strategy: &CollisionResolutionStrategy,
) -> miette::Result<()> {
    fs::create_dir_all(dest_dir)
        .into_diagnostic()
        .wrap_err(format!(
            "Unable to create merge directory: {}",
            dest_dir.to_string_lossy()
        ))?;

    // Collect all children from all source directories.
    // child_name -> list of full paths to that child across sources.
    let mut children: HashMap<String, Vec<PathBuf>> = HashMap::new();
    for source in sources {
        if !source.is_dir() {
            continue;
        }
        for entry in fs::read_dir(source).into_diagnostic().wrap_err(format!(
            "Unable to read conflict source directory {}",
            source.to_string_lossy()
        ))? {
            let entry = entry.into_diagnostic()?;
            let name = entry.file_name().to_string_lossy().to_string();
            if name == "__pycache__" {
                continue;
            }
            children.entry(name).or_default().push(entry.path());
        }
    }

    for (name, paths) in &children {
        let dest_child = dest_dir.join(name);
        if dest_child.exists() || dest_child.is_symlink() {
            continue;
        }

        if paths.len() == 1 {
            // Only one source provides this child — single symlink,
            // resolved to canonical path to skip runfiles indirection.
            let target = resolve_symlink_target(&paths[0]);
            std::os::unix::fs::symlink(&target, &dest_child)
                .into_diagnostic()
                .wrap_err(format!(
                    "Unable to create symlink: {} -> {}",
                    dest_child.to_string_lossy(),
                    target.to_string_lossy()
                ))?;
        } else if paths[0].is_dir() {
            // Multiple sources provide this directory — recurse to merge.
            merge_namespace_conflict(paths, &dest_child, collision_strategy)?;
        } else {
            // Multiple sources provide the same file (e.g. namespace __init__.py).
            // These are typically identical markers. Symlink to the first,
            // resolved to canonical path.
            let target = resolve_symlink_target(&paths[0]);
            std::os::unix::fs::symlink(&target, &dest_child)
                .into_diagnostic()
                .wrap_err(format!(
                    "Unable to create symlink for shared file: {} -> {}",
                    dest_child.to_string_lossy(),
                    target.to_string_lossy()
                ))?;
        }
    }

    Ok(())
}

/// Resolve a path to its canonical target to avoid symlink chains.
///
/// For files and directory symlinks: canonicalize() follows all symlinks.
/// For real directories (Bazel runfiles — real dirs with per-file symlinks
/// inside): probe inside to find the external/ equivalent via
/// resolve_to_external().
fn resolve_symlink_target(path: &Path) -> PathBuf {
    if path.is_dir() && !path.is_symlink() {
        // Real directory in runfiles — files inside are symlinks to external/.
        resolve_to_external(path).unwrap_or_else(|| {
            path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
        })
    } else {
        // File or directory symlink — canonicalize directly.
        path.canonicalize()
            .unwrap_or_else(|_| path.to_path_buf())
    }
}

pub fn create_symlinks(
    dir: &Path,
    root_dir: &Path,
    dst_dir: &Path,
    collision_strategy: &CollisionResolutionStrategy,
) -> miette::Result<()> {
    // Create this directory at the destination.
    let tgt_dir = dst_dir.join(dir.strip_prefix(root_dir).unwrap());
    std::fs::create_dir_all(&tgt_dir)
        .into_diagnostic()
        .wrap_err(format!(
            "Unable to create parent directory for symlink: {}",
            tgt_dir.to_string_lossy()
        ))?;

    // Recurse.
    let read_dir = fs::read_dir(dir).into_diagnostic().wrap_err(format!(
        "Unable to read directory {}",
        dir.to_string_lossy()
    ))?;

    for entry in read_dir {
        let entry = entry.into_diagnostic().wrap_err(format!(
            "Unable to read directory entry {}",
            dir.to_string_lossy()
        ))?;

        let path = entry.path();

        // If this path is a directory, recurse into it, else symlink the file now.
        // We must ignore the `__init__.py` file in the root_dir because these are Bazel inserted
        // `__init__.py` files in the root site-packages directory. The site-packages directory
        // itself is not a regular package and is not supposed to have an `__init__.py` file.
        if path.is_dir() {
            create_symlinks(&path, root_dir, dst_dir, collision_strategy)?;
        }
        // rules_python runfiles helper needs some special handling when consumed as pip dependency.
        // See: https://github.com/aspect-build/rules_py/issues/377
        // See: https://github.com/bazelbuild/rules_python/pull/2115
        else if path.as_path().ends_with(RULES_PYTHON_INIT_PATH) {
            // Instead of symlinking the __init__.py file from its original location to the venv site-packages,
            // we write a shim __init__.py that makes the runfiles pypi library work with rules_py.
            fs::write(
                dst_dir.join(RULES_PYTHON_INIT_PATH),
                RULES_PYTHON_RUNFILES_INIT_SHIM,
            )
            .into_diagnostic()
            .wrap_err("Unable to write to runfiles __init__.py file")?;
        } else if dir != root_dir || entry.file_name() != "__init__.py" {
            create_symlink(&entry, root_dir, dst_dir, collision_strategy)?;
        }
    }
    Ok(())
}

fn create_symlink(
    e: &DirEntry,
    root_dir: &Path,
    dst_dir: &Path,
    collision_strategy: &CollisionResolutionStrategy,
) -> miette::Result<()> {
    let tgt = e.path();
    let link = dst_dir.join(tgt.strip_prefix(root_dir).unwrap());

    fn conflict_report(link: &Path, tgt: &Path, severity: Severity) -> miette::Report {
        const SITE_PACKAGES: &str = "site-packages/";

        let link_str = link.to_str().unwrap();
        let tgt_str = tgt.to_str().unwrap();

        let link_span_range = link
            .to_str()
            .and_then(|s| s.split_once(SITE_PACKAGES))
            .map(|s| s.1)
            .map(|s| (link_str.len() - s.len() - SITE_PACKAGES.len())..link_str.len())
            .unwrap();

        let conflict_span_range = tgt
            .to_str()
            .and_then(|s| s.split_once(SITE_PACKAGES))
            .map(|s| s.1)
            .map(|s| {
                (link_str.len() + tgt_str.len() - s.len() - SITE_PACKAGES.len() + 1)
                    ..tgt_str.len() + link_str.len() + 1
            })
            .unwrap();

        let mut diag = MietteDiagnostic::new("Conflicting symlinks found when attempting to create venv. More than one package provides the file at these paths".to_string())
            .with_severity(severity)
            .with_labels([
                LabeledSpan::at(link_span_range, "Existing file in virtual environment"),
                LabeledSpan::at(conflict_span_range, "Next file to link"),
            ]);

        diag = if severity == Severity::Error {
            diag.with_help("Set `package_collisions = \"warning\"` on the binary or test rule to downgrade this error to a warning")
        } else {
            diag.with_help("Set `package_collisions = \"ignore\"` on the binary or test rule to ignore this warning")
        };

        miette!(diag).with_source_code(format!(
            "{}\n{}",
            link.to_str().unwrap(),
            tgt.to_str().unwrap()
        ))
    }

    if link.exists() {
        // If the link already exists and is the same file, then there is no need to link this new one.
        // Assume that if the files are the same, then there is no need to warn or error.
        if is_same_file(&link, &tgt)? {
            return Ok(());
        }

        match collision_strategy {
            CollisionResolutionStrategy::LastWins(warn) => {
                fs::remove_file(&link)
                    .into_diagnostic()
                    .wrap_err(
                        miette!(
                            "Unable to remove conflicting symlink in site-packages. Existing symlink {} conflicts with new target {}",
                            link.to_string_lossy(),
                            tgt.to_string_lossy()
                        )
                    )?;

                if *warn {
                    let conflicts = conflict_report(&link, &tgt, Severity::Warning);
                    eprintln!("{:?}", conflicts);
                }
            }
            CollisionResolutionStrategy::Error => {
                // If the link already exists, then there is going to be a conflict.
                let conflicts = conflict_report(&link, &tgt, Severity::Error);
                return Err(conflicts);
            }
        };
    }

    std::os::unix::fs::symlink(&tgt, &link)
        .into_diagnostic()
        .wrap_err(format!(
            "Unable to create symlink: {} -> {}",
            tgt.to_string_lossy(),
            link.to_string_lossy()
        ))?;

    Ok(())
}

/// Resolve a runfiles site-packages directory to its external/ equivalent
/// by following per-file symlinks to find where the real files live.
///
/// Bazel's runfiles tree has real directories containing per-file symlinks:
///   runfiles/.../site-packages/pkg/  (real dir)
///     __init__.py  (symlink → external/.../site-packages/pkg/__init__.py)
///
/// canonicalize() on the directory returns the runfiles path (it's real).
/// We need to probe a file inside, canonicalize it, and strip the suffix
/// to recover the external/ site-packages path.
fn resolve_to_external(site_packages_dir: &Path) -> Option<PathBuf> {
    fn find_file_symlink(dir: &Path, depth: u32) -> Option<(PathBuf, PathBuf)> {
        if depth > 3 {
            return None;
        }
        for entry in fs::read_dir(dir).ok()? {
            let entry = entry.ok()?;
            let path = entry.path();
            if path.is_symlink()
                && !path.is_dir()
                && path.file_name().map_or(true, |n| n != "__init__.py")
            {
                let canonical = path.canonicalize().ok()?;
                return Some((path, canonical));
            }
            if path.is_dir() && !path.is_symlink() {
                if let Some(found) = find_file_symlink(&path, depth + 1) {
                    return Some(found);
                }
            }
        }
        None
    }

    let (file_in_runfiles, canonical) = find_file_symlink(site_packages_dir, 0)?;
    // file_in_runfiles = .../site-packages/cloudpathlib/__init__.py
    // canonical        = .../external/.../site-packages/cloudpathlib/__init__.py
    // relative         = cloudpathlib/__init__.py
    let relative = file_in_runfiles.strip_prefix(site_packages_dir).ok()?;
    let depth = relative.components().count();
    let mut external_base = canonical.as_path();
    for _ in 0..depth {
        external_base = external_base.parent()?;
    }
    Some(external_base.to_path_buf())
}

fn is_same_file(p1: &Path, p2: &Path) -> miette::Result<bool> {
    let f1 = File::open(p1)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p1.to_string_lossy()))?;
    let f2 = File::open(p2)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p2.to_string_lossy()))?;

    // Check file size is the same.
    if f1.metadata().unwrap().len() != f2.metadata().unwrap().len() {
        return Ok(false);
    }

    // Compare bytes from the two files in pairs, given that they have the same number of bytes.
    let buf1 = BufReader::new(f1);
    let buf2 = BufReader::new(f2);
    for (b1, b2) in buf1.bytes().zip(buf2.bytes()) {
        if b1.unwrap() != b2.unwrap() {
            return Ok(false);
        }
    }

    return Ok(true);
}
