use std::{
    collections::{HashMap, HashSet},
    fs::{self, DirEntry, File},
    io::{BufRead, BufReader, BufWriter, Read, Write},
    path::{Path, PathBuf},
};

use miette::{miette, Context, IntoDiagnostic, LabeledSpan, MietteDiagnostic, Severity};

const RULES_PYTHON_INIT_PATH: &str = "runfiles/__init__.py";
const RULES_PYTHON_RUNFILES_INIT_SHIM: &str = r#"
# Generated by rules_py venv for rules_python compatibility
# See: https://github.com/bazelbuild/rules_python/pull/2115
# See: https://github.com/aspect-build/rules_py/issues/377
from . import runfiles
def _FindPythonRunfilesRoot():
    root = __file__
    # The original implementation of this function in rules_python expects the runfiles root to be 4 directories up from the current file.
    # but in rules_py there is additional two segments that it needs to go up to  find the runfiles root.
    # bazel-bin/py/tests/external-deps/foo.runfiles/.foo.venv/lib/python3.9/site-packages/runfiles
    # ╰─────────────────────┬─────────────────────╯╰───┬───╯╰─────────────┬─────────────╯╰───┬───╯
    #             bazel runfiles root              venv root    Python packages root   Python package
    
    for _ in range("rules_python/python/runfiles/runfiles.py".count("/") + 3):
        root = os.path.dirname(root)
    return root

runfiles._FindPythonRunfilesRoot = _FindPythonRunfilesRoot

from .runfiles import *
"#;

/// Strategy that will be used when creating the virtual env symlink and
/// a collision is found.
#[derive(Default, Debug, PartialEq)]
pub enum CollisionResolutionStrategy {
    /// Collisions cause a hard error.
    #[default]
    Error,

    /// The last file to provide a target wins.
    /// If inner is true, then a warning is produced, otherwise the last target silently wins.
    LastWins(bool),
}

/// Options for the creation of the `site-packages` folder layout.
#[derive(Default, Debug)]
pub struct SitePackageOptions {
    /// Destination path, where the `site-package` folder lives.
    pub dest: PathBuf,

    /// Collision strategy determining the action taken when sylinks in the venv collide.
    pub collision_strategy: CollisionResolutionStrategy,
}

pub struct PthFile {
    pub src: PathBuf,
    pub prefix: Option<String>,
}

impl PthFile {
    pub fn new(src: &Path, prefix: Option<String>) -> PthFile {
        Self {
            src: src.to_path_buf(),
            prefix,
        }
    }

    // This is the _old_ machinery for setting up a virtualenv, which assumes
    // that the path file consists of pre-relativized paths. The new machinery
    // does that math on the Rust side rather than on the Bazel side, so the two
    // are `.pth` file incompatible.
    //
    // Top-level symlink strategy: instead of recursively symlinking every file
    // from every site-packages directory, create one symlink per top-level
    // package/module. Only when multiple site-packages dirs provide the same
    // top-level name (namespace package conflict) do we fall back to recursive
    // symlink-merging for that name.
    pub fn set_up_site_packages_dynamic(&self, opts: SitePackageOptions) -> miette::Result<()> {
        let dest = &opts.dest;

        let source_pth = File::open(self.src.as_path())
            .into_diagnostic()
            .wrap_err("Unable to open source .pth file")?;
        let dest_pth = File::create(dest.join(self.src.file_name().expect(".pth must be a file")))
            .into_diagnostic()
            .wrap_err("Unable to create destination .pth file")?;

        let mut reader = BufReader::new(source_pth);
        let mut writer = BufWriter::new(dest_pth);
        let path_prefix = self.prefix.as_ref().map(|pre| Path::new(pre));

        // Names to skip entirely (never symlink, never count as conflicts).
        let skip_names: HashSet<&str> =
            HashSet::from(["__pycache__", "__init__.py", "__pypackages__"]);

        // Suffixes to exclude from conflict detection but still symlink.
        let metadata_suffixes = [".dist-info", ".egg-info"];

        // Phase 1: Read all entries; for site-packages dirs, collect top-level names
        // and track which source dirs provide them.
        let mut entries: Vec<(PathBuf, bool)> = Vec::new();
        let mut toplevel_to_sources: HashMap<String, Vec<PathBuf>> = HashMap::new();

        let mut line = String::new();
        while reader.read_line(&mut line).unwrap() > 0 {
            let entry = path_prefix
                .map(|pre| pre.join(line.trim()))
                .unwrap_or_else(|| PathBuf::from(line.trim()));

            line.clear();

            let is_site = entry.file_name().map_or(false, |n| n == "site-packages");
            if is_site {
                let resolved = dest
                    .join(&entry)
                    .canonicalize()
                    .into_diagnostic()
                    .wrap_err(format!(
                        "Unable to resolve site-packages path {} relative to {}",
                        entry.display(),
                        dest.display(),
                    ))?;

                for child in fs::read_dir(&resolved).into_diagnostic().wrap_err(format!(
                    "Unable to read site-packages directory {}",
                    resolved.display()
                ))? {
                    let child = child.into_diagnostic()?;
                    let name = child.file_name().to_string_lossy().to_string();
                    if skip_names.contains(name.as_str())
                        || metadata_suffixes.iter().any(|s| name.ends_with(s))
                    {
                        continue;
                    }
                    toplevel_to_sources
                        .entry(name)
                        .or_default()
                        .push(resolved.clone());
                }
            }
            entries.push((entry, is_site));
        }

        // Phase 2: Identify conflicting names (provided by more than one source dir).
        let conflicting_names: HashSet<String> = toplevel_to_sources
            .iter()
            .filter(|(_, sources)| sources.len() > 1)
            .map(|(name, _)| name.clone())
            .collect();

        // Phase 3: For each site-packages dir, create top-level symlinks for
        // non-conflicting names and recursively merge conflicting ones.
        // Non-site-packages entries are written as .pth lines (unchanged).
        for (entry, is_site) in &entries {
            if !is_site {
                writeln!(writer, "{}", entry.to_string_lossy())
                    .into_diagnostic()
                    .wrap_err("Unable to write new .pth file entry")?;
                continue;
            }

            let src_dir = dest
                .join(entry)
                .canonicalize()
                .into_diagnostic()
                .wrap_err(format!(
                    "Unable to resolve site-packages path {}",
                    entry.display(),
                ))?;

            for child in fs::read_dir(&src_dir).into_diagnostic()? {
                let child = child.into_diagnostic()?;
                let name = child.file_name().to_string_lossy().to_string();

                // Skip caches and Bazel-inserted __init__.py.
                if skip_names.contains(name.as_str()) {
                    continue;
                }

                let child_path = child.path();

                if conflicting_names.contains(&name) {
                    // Namespace conflict: recursively symlink-merge so all
                    // providers contribute their files under this name.
                    if child_path.is_dir() {
                        create_symlinks(
                            &child_path,
                            &src_dir,
                            dest,
                            &opts.collision_strategy,
                        )?;
                    } else {
                        create_symlink(
                            &child,
                            &src_dir,
                            dest,
                            &opts.collision_strategy,
                        )?;
                    }
                } else {
                    // No conflict: single top-level symlink.
                    let link = dest.join(&name);
                    if !link.exists() {
                        std::os::unix::fs::symlink(&child_path, &link)
                            .into_diagnostic()
                            .wrap_err(format!(
                                "Unable to create top-level symlink: {} -> {}",
                                link.display(),
                                child_path.display(),
                            ))?;
                    }
                }
            }
        }

        Ok(())
    }
}

pub fn create_symlinks(
    dir: &Path,
    root_dir: &Path,
    dst_dir: &Path,
    collision_strategy: &CollisionResolutionStrategy,
) -> miette::Result<()> {
    // Create this directory at the destination.
    let tgt_dir = dst_dir.join(dir.strip_prefix(root_dir).unwrap());
    std::fs::create_dir_all(&tgt_dir)
        .into_diagnostic()
        .wrap_err(format!(
            "Unable to create parent directory for symlink: {}",
            tgt_dir.to_string_lossy()
        ))?;

    // Recurse.
    let read_dir = fs::read_dir(dir).into_diagnostic().wrap_err(format!(
        "Unable to read directory {}",
        dir.to_string_lossy()
    ))?;

    for entry in read_dir {
        let entry = entry.into_diagnostic().wrap_err(format!(
            "Unable to read directory entry {}",
            dir.to_string_lossy()
        ))?;

        let path = entry.path();

        // If this path is a directory, recurse into it, else symlink the file now.
        // We must ignore the `__init__.py` file in the root_dir because these are Bazel inserted
        // `__init__.py` files in the root site-packages directory. The site-packages directory
        // itself is not a regular package and is not supposed to have an `__init__.py` file.
        if path.is_dir() {
            create_symlinks(&path, root_dir, dst_dir, collision_strategy)?;
        }
        // rules_python runfiles helper needs some special handling when consumed as pip dependency.
        // See: https://github.com/aspect-build/rules_py/issues/377
        // See: https://github.com/bazelbuild/rules_python/pull/2115
        else if path.as_path().ends_with(RULES_PYTHON_INIT_PATH) {
            // Instead of symlinking the __init__.py file from its original location to the venv site-packages,
            // we write a shim __init__.py that makes the runfiles pypi library work with rules_py.
            fs::write(
                dst_dir.join(RULES_PYTHON_INIT_PATH),
                RULES_PYTHON_RUNFILES_INIT_SHIM,
            )
            .into_diagnostic()
            .wrap_err("Unable to write to runfiles __init__.py file")?;
        } else if dir != root_dir || entry.file_name() != "__init__.py" {
            create_symlink(&entry, root_dir, dst_dir, collision_strategy)?;
        }
    }
    Ok(())
}

fn create_symlink(
    e: &DirEntry,
    root_dir: &Path,
    dst_dir: &Path,
    collision_strategy: &CollisionResolutionStrategy,
) -> miette::Result<()> {
    let tgt = e.path();
    let link = dst_dir.join(tgt.strip_prefix(root_dir).unwrap());

    fn conflict_report(link: &Path, tgt: &Path, severity: Severity) -> miette::Report {
        const SITE_PACKAGES: &str = "site-packages/";

        let link_str = link.to_str().unwrap();
        let tgt_str = tgt.to_str().unwrap();

        let link_span_range = link
            .to_str()
            .and_then(|s| s.split_once(SITE_PACKAGES))
            .map(|s| s.1)
            .map(|s| (link_str.len() - s.len() - SITE_PACKAGES.len())..link_str.len())
            .unwrap();

        let conflict_span_range = tgt
            .to_str()
            .and_then(|s| s.split_once(SITE_PACKAGES))
            .map(|s| s.1)
            .map(|s| {
                (link_str.len() + tgt_str.len() - s.len() - SITE_PACKAGES.len() + 1)
                    ..tgt_str.len() + link_str.len() + 1
            })
            .unwrap();

        let mut diag = MietteDiagnostic::new("Conflicting symlinks found when attempting to create venv. More than one package provides the file at these paths".to_string())
            .with_severity(severity)
            .with_labels([
                LabeledSpan::at(link_span_range, "Existing file in virtual environment"),
                LabeledSpan::at(conflict_span_range, "Next file to link"),
            ]);

        diag = if severity == Severity::Error {
            diag.with_help("Set `package_collisions = \"warning\"` on the binary or test rule to downgrade this error to a warning")
        } else {
            diag.with_help("Set `package_collisions = \"ignore\"` on the binary or test rule to ignore this warning")
        };

        miette!(diag).with_source_code(format!(
            "{}\n{}",
            link.to_str().unwrap(),
            tgt.to_str().unwrap()
        ))
    }

    if link.exists() {
        // If the link already exists and is the same file, then there is no need to link this new one.
        // Assume that if the files are the same, then there is no need to warn or error.
        if is_same_file(&link, &tgt)? {
            return Ok(());
        }

        match collision_strategy {
            CollisionResolutionStrategy::LastWins(warn) => {
                fs::remove_file(&link)
                    .into_diagnostic()
                    .wrap_err(
                        miette!(
                            "Unable to remove conflicting symlink in site-packages. Existing symlink {} conflicts with new target {}",
                            link.to_string_lossy(),
                            tgt.to_string_lossy()
                        )
                    )?;

                if *warn {
                    let conflicts = conflict_report(&link, &tgt, Severity::Warning);
                    eprintln!("{:?}", conflicts);
                }
            }
            CollisionResolutionStrategy::Error => {
                // If the link already exists, then there is going to be a conflict.
                let conflicts = conflict_report(&link, &tgt, Severity::Error);
                return Err(conflicts);
            }
        };
    }

    std::os::unix::fs::symlink(&tgt, &link)
        .into_diagnostic()
        .wrap_err(format!(
            "Unable to create symlink: {} -> {}",
            tgt.to_string_lossy(),
            link.to_string_lossy()
        ))?;

    Ok(())
}

fn is_same_file(p1: &Path, p2: &Path) -> miette::Result<bool> {
    let f1 = File::open(p1)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p1.to_string_lossy()))?;
    let f2 = File::open(p2)
        .into_diagnostic()
        .wrap_err(format!("Unable to open file {}", p2.to_string_lossy()))?;

    // Check file size is the same.
    if f1.metadata().unwrap().len() != f2.metadata().unwrap().len() {
        return Ok(false);
    }

    // Compare bytes from the two files in pairs, given that they have the same number of bytes.
    let buf1 = BufReader::new(f1);
    let buf2 = BufReader::new(f2);
    for (b1, b2) in buf1.bytes().zip(buf2.bytes()) {
        if b1.unwrap() != b2.unwrap() {
            return Ok(false);
        }
    }

    return Ok(true);
}
